### ISSUE TITLE
Great Start

### ISSUE THREAD

**Issue by GeorgeSpiggott** [lilbud/carbon-es-de#1]
This looks to be coming along well, thanks. I have two queries.

Is it possible to make the various system art full colour like the Retropie version?

I see that some art is missing, Nintendo 3DS (controller and system) and PS4 and PSVita (controller). Do you have access to art for these?

**Comment by lilbud** [comment]
I had the full color logos, but many of them are black/dark colors and blend into the background. So I switched to the white logos which can be colored to match system color. I'm not sure how to include those logos without having to edit all 150+ of them to not blend in. 

As for the missing art, all I have is what was provided with the original theme. The creator Rookervik drew all those controllers from scratch, and he hasn't been active in a few years now I think. Only option would be taking the controllers from the slate theme or something, but those are pictures, not line drawings. So they wouldn't match.

**Comment by GeorgeSpiggott** [comment]
There's some additional art that Duimon did here: https://forums.libretro.com/t/emulationstation-carbon-theme-controller-art/34269/53

In the mean time for the missing PS4 and PSVita I have copied the PS3 and PSP controller art as they're similar looking. i'll experiment with mixing in coloured images for the system art.

**Comment by lilbud** [comment]
I added in 3ds and ngcd from that set, the rest I had.

**Comment by GeorgeSpiggott** [comment]
Glad it was some use. I have also spotted that it is looking for "scroll.wav" in the wrong place, it is looking in assets not assets/sounds.

**Comment by lilbud** [comment]
thanks, fixed that
