### ISSUE TITLE
Issues with using Carbon in ES-DE 2.2.0-alpha

### ISSUE THREAD

**Issue by leonstyhre** [lilbud/carbon-es-de#2]
Hi!

I'm currently working on the 2.2.0 release where I've completely removed support for legacy EmulationStation themes.
As part of this I have found that you have a small issue in your theme that makes it not load any longer, and that is that you've added a legacy `scrollSound` property to the `textlist` element. Could you please remove this? The custom scroll sound will still work as you have correctly defined it in the `all` view as well.

There is another small typo too which generates a warning on theme loading, and that is that you have defined `<trigger>noVideo</trigger>` in capabilities.xml but it should be `<trigger>noVideos</trigger>`

Finally something that is more of a request than an error, would it be possible to enable sound for the videos in the gamelist view? It's quite silent with no videos playing any sounds. If you don't like to have sounds in your gamelist views you can instead choose to turn that off from the Sound Settings menu, as it is now people would need to customize Carbon to enable sounds.

Thanks! :)

**Comment by lilbud** [comment]
Hey,

Sorry for the delay, I didn't even see the email that said about an issue (hence this being over a week later).

Fixed the two things you mentioned, and reenabled video audio, if you redownload it should be all good.

Thanks

**Comment by leonstyhre** [comment]
Thanks a lot for this, it works perfect now!
