### ISSUE TITLE
Add support for all ES-DE systems + badges

### ISSUE THREAD

**Issue by leonstyhre** [lilbud/carbon-es-de#3]
Hi!

I'm interested in adding your port of the Carbon theme to the ES-DE official themes list and the built-in theme downloader, but it's currently missing a number of systems including those I've added for the upcoming 2.2.0 release.

Would you be willing to include support for all systems to this theme? You can find the system logo repository here that is really helpful for achieving this:

https://gitlab.com/es-de/themes/system-logos

And as well, would it be possible to add support for badges? This is really essential functionality in ES-DE and it's easy to add it in. Either you could use the default badge graphics or borrow badge graphics from one of the other ES-DE themes. This latter approach will probably look best for matching them with the overall Carbon theme design.

Thanks! :)

**Comment by lilbud** [comment]
Added the new systems. How I have the theme set-up is that all that is needed for a new system is just adding the proper logos (Everything else is variable based and should just work)

I grabbed the badges from the Epic Noir Next theme.

I added the code for the badges but can't get them to appear. I'm on the latest ES-DE and have all my games loaded in with metadata, below is where they *should* appear, at least that's where I placed them in the theme.xml.
![image](https://github.com/lilbud/carbon-es-de/assets/9311410/8c69d7ff-f69f-46d5-9dae-12b25d901016)

**Comment by leonstyhre** [comment]
Thanks for adding the system support! As for the badges something is wrong with your configuration (I just tested the theme), check es_log.txt for warnings and errors.

**Comment by lilbud** [comment]
> Thanks for adding the system support! As for the badges something is wrong with your configuration (I just tested the theme), check es_log.txt for warnings and errors.

yeah I reinstalled windows recently and have been dealing with getting everything set up again and working, plus I haven't used ES in a while so I'll have to go in and get everything back to how I had it.

**Comment by leonstyhre** [comment]
But there is something wrong, it says that the badge files you have specified are missing, so could you please open the issue again and investigate the problem?

Otherwise it looks great, except that you missed a single system, "laserdisc" so if you could add that logo too then the theme is complete.
When you've managed to get the badges working I'll go ahead and add the theme to the themes list.
Thanks!

**Comment by lilbud** [comment]
> But there is something wrong, it says that the badge files you have specified are missing, so could you please open the issue again and investigate the problem?
> 
> Otherwise it looks great, except that you missed a single system, "laserdisc" so if you could add that logo too then the theme is complete. When you've managed to get the badges working I'll go ahead and add the theme to the themes list. Thanks!

I checked the log and there is no mention of missing badge files, not even in debug mode. The files are there, and the theme points to the right path. I have other items in that folder and they load no issue
![image](https://github.com/lilbud/carbon-es-de/assets/9311410/17074a75-a0ce-40f2-9dcf-ac8619ff5024)

**Comment by leonstyhre** [comment]
That's strange, I get a lot of warnings like these:
`Oct 20 22:50:53 Warn:   BadgeComponent: Invalid theme configuration, property "customBadgeIcon" for element "badges", image does not exist: "/home/leon/.emulationstation/themes/carbon-es-de/assets/img/badges/badge-collection.svg"`

**Comment by lilbud** [comment]
I searched my log file and found no mention of badges. I'm on the latest ES-DE version, and have games with metadata marked as favorites as well. So it should be looking for the badges right?

**Comment by leonstyhre** [comment]
Btw, you should never store themes directly into the themes directory, they should always go into .emulationstation\themes\ maybe that is somehow part of the problem.

**Comment by leonstyhre** [comment]
Because if you have a copy of carbon in .emulationstation\themes\ it will take precedence and be loaded instead of whatever you place directly into themes\ as that is really only intended for themes shipped with the installation, i.e. Modern and Slate.

**Comment by leonstyhre** [comment]
As you can see here, there's not even a badge directory in the repository:

https://github.com/lilbud/carbon-es-de/tree/main/assets/img

**Comment by lilbud** [comment]
forgot to add to the repo. But even still, doesn't matter where my themes are located, I don't see any messages about missing badges

**Comment by leonstyhre** [comment]
Thanks for adding the badge images to the repository, the messages about missing files are now gone.

The problem you have is that you have placed the badges off screen, something like the following works:
```
<badges name="badges">
    <origin>1 0</origin>
    <pos>0.953 0.665</pos>
    <size>0.23 0.02962962962963</size>
    <itemMargin>0.005208333333333 -1</itemMargin>
    <lines>1</lines>
    <itemsPerLine>9</itemsPerLine>
    <slots>all</slots>
    <customBadgeIcon badge="folder">./assets/img/badges/badge-folder.svg</customBadgeIcon>
    <customBadgeIcon badge="broken">./assets/img/badges/badge-broken.svg</customBadgeIcon>
    <customBadgeIcon badge="completed">./assets/img/badges/badge-completed.svg</customBadgeIcon>
    <customBadgeIcon badge="favorite">./assets/img/badges/badge-favorite.svg</customBadgeIcon>
    <customBadgeIcon badge="kidgame">./assets/img/badges/badge-kidgame.svg</customBadgeIcon>
    <customBadgeIcon badge="collection">./assets/img/badges/badge-collection.svg</customBadgeIcon>
    <customBadgeIcon badge="controller">./assets/img/badges/badge-controller.svg</customBadgeIcon>
    <customBadgeIcon badge="altemulator">./assets/img/badges/badge-altemulator.svg</customBadgeIcon>
    <customBadgeIcon badge="manual">./assets/img/badges/badge-manual.svg</customBadgeIcon>
    <badgeIconColor>${mainColor}c0</badgeIconColor>
    <controllerSize>0.8</controllerSize>
    <folderLinkSize>0.8</folderLinkSize>
    <horizontalAlignment>right</horizontalAlignment>
</badges>
```

You may need to fine tune this for exact placement of course. It's also a good idea to add explicit support for some aspect ratios like 16:10 and 4:3 in addition to the 16:9 ratio as the theme doesn't look right at 4:3 at the moment for example.

Could you also please add the missing laserdisc logo? Thanks!

**Comment by leonstyhre** [comment]
Actually I just realized that the laserdisc logo is missing from the logo repository, I'll make sure it's added!

**Comment by leonstyhre** [comment]
I'm attaching the white laserdisc logo here until the repo has been updated.

![laserdisc_white](https://github.com/lilbud/carbon-es-de/assets/94190869/9de9557c-e0c4-45e8-94b0-544a0214f599)

**Comment by lilbud** [comment]
added the new Laserdisc logo, and implemented that new badge code you sent. Not sure why they didn't show up before, as a 0,0 origin should start top left and draw them on screen. It is fixed now.

![image](https://github.com/lilbud/carbon-es-de/assets/9311410/80e77d48-8466-464c-b798-a5a685f98748)

As for the aspect ratios, my classes have me swamped with work so I'm not going to be able to get to that for quite a while. Maybe someone else could that on in the meantime as I'm not sure when I'll be free to get to it.

**Comment by leonstyhre** [comment]
Thanks for the update! It's not a big problem with the lack of aspect ratio support, the theme looks good at 16:9 and 16:10 which are the most important ratios anyway. If you have some time later on to add fine tuning and support for 4:3 and widescreen resolutions then that's just an added bonus.

There is one problem however, it seems as if you took the colored version of the laserdisc logo instead of the white one, so it shows up as black now in the theme which makes it basically invisible when entering the system, could you please replace it with this file?

https://gitlab.com/es-de/themes/system-logos/-/blob/master/system-logo-white/laserdisc.svg?ref_type=heads

When you've fixed this I'm ready to add it to the themes list/theme downloader. What credits should I include for the theme, for sure I'll add "lilbud" but I guess some other people have worked on this theme previously?

Thanks!

**Comment by leonstyhre** [comment]
I just found one more (possible) minor issue, you have not applied color shift to the smaller version of the controller shown in the upper right corner of the gamelist view. It can be seen in the screenshot you just pasted above.

Unless this is intentional, could you then please add color shifting? But if this design is intentional then you can of course keep it as is.

Thanks :)

**Comment by lilbud** [comment]
> Thanks for the update! It's not a big problem with the lack of aspect ratio support, the theme looks good at 16:9 and 16:10 which are the most important ratios anyway. If you have some time later on to add fine tuning and support for 4:3 and widescreen resolutions then that's just an added bonus.
> 
> There is one problem however, it seems as if you took the colored version of the laserdisc logo instead of the white one, so it shows up as black now in the theme which makes it basically invisible when entering the system, could you please replace it with this file?
> 
> https://gitlab.com/es-de/themes/system-logos/-/blob/master/system-logo-white/laserdisc.svg?ref_type=heads
> 
> When you've fixed this I'm ready to add it to the themes list/theme downloader. What credits should I include for the theme, for sure I'll add "lilbud" but I guess some other people have worked on this theme previously?
> 
> Thanks!

Added the fixed logo. As for credits, I believe Rookervik was the one who designed the theme initially. So, that is where credit should go. I think I also implemented the color variants from his Luminous theme as well. 

Kinda crazy that it is 6yrs later and the theme is still being used. Seems like forever ago I was working on RetroPie and stuff.


> I just found one more (possible) minor issue, you have not applied color shift to the smaller version of the controller shown in the upper right corner of the gamelist view. It can be seen in the screenshot you just pasted above.
> 
> Unless this is intentional, could you then please add color shifting? But if this design is intentional then you can of course keep it as is.
> 
> Thanks :)

That is intentional, copied over from the original theme. I tried my best to make no major layout changes when porting it over. Only changes I made was code cleanup, coloring the logos, and the color variants.

**Comment by leonstyhre** [comment]
Thanks for fixing the logo, I've now added the theme to the theme downloader and themes list. It's a classic design and with ES-DE dropping legacy theme support with the 2.2.0 release I think it's nice that the Carbon theme is available for anyone coming from RetroPie that may have nostalgic memories of this theme!
